INSERT INTO `symptomlist` VALUES (404684003,'Clinical finding (finding)');
INSERT INTO `symptomlist` VALUES ( 109006,'Anxiety disorder of childhood OR adolescence');
INSERT INTO `symptomlist` VALUES ( 122003,'Choroidal hemorrhage');
INSERT INTO `symptomlist` VALUES ( 127009,'Spontaneous abortion with laceration of cervix');
INSERT INTO `symptomlist` VALUES ( 129007,'Homoiothermia');
INSERT INTO `symptomlist` VALUES ( 134006,'Decreased hair growth');
INSERT INTO `symptomlist` VALUES ( 140004,'Chronic pharyngitis');
INSERT INTO `symptomlist` VALUES ( 144008,'Normal peripheral vision');
INSERT INTO `symptomlist` VALUES ( 147001,'Superficial foreign body of scrotum without major open wound but with infection');
INSERT INTO `symptomlist` VALUES ( 150003,'Abnormal bladder continence');
INSERT INTO `symptomlist` VALUES ( 151004,'Gonococcal meningitis');
INSERT INTO `symptomlist` VALUES ( 162004,'Severe manic bipolar I disorder without psychotic features');
INSERT INTO `symptomlist` VALUES ( 165002,'Accident-prone');
INSERT INTO `symptomlist` VALUES ( 168000,'Typhlolithiasis');
INSERT INTO `symptomlist` VALUES ( 171008,'Injury of ascending right colon without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 172001,'Endometritis following molar AND/OR ectopic pregnancy');
INSERT INTO `symptomlist` VALUES ( 175004,'Supraorbital neuralgia');
INSERT INTO `symptomlist` VALUES ( 177007,'Poisoning by sawfly larvae');
INSERT INTO `symptomlist` VALUES ( 179005,'Apraxia of dressing');
INSERT INTO `symptomlist` VALUES ( 181007,'Hemorrhagic bronchopneumonia');
INSERT INTO `symptomlist` VALUES ( 183005,'Autoimmune pancytopenia');
INSERT INTO `symptomlist` VALUES ( 184004,'Withdrawal arrhythmia');
INSERT INTO `symptomlist` VALUES ( 188001,'Injury of intercostal artery');
INSERT INTO `symptomlist` VALUES ( 192008,'Congenital syphilitic hepatomegaly');
INSERT INTO `symptomlist` VALUES ( 193003,'Benign hypertensive renal disease');
INSERT INTO `symptomlist` VALUES ( 195005,'Illegal abortion with endometritis');
INSERT INTO `symptomlist` VALUES ( 198007,'Disease due to Filoviridae');
INSERT INTO `symptomlist` VALUES ( 199004,'Decreased lactation');
INSERT INTO `symptomlist` VALUES ( 208008,'Neurocutaneous melanosis sequence');
INSERT INTO `symptomlist` VALUES ( 216004,'Delusion of persecution');
INSERT INTO `symptomlist` VALUES ( 219006,'Alcohol user');
INSERT INTO `symptomlist` VALUES ( 222008,'Acute epiglottitis with obstruction');
INSERT INTO `symptomlist` VALUES ( 223003,'Tumor of body of uterus affecting pregnancy');
INSERT INTO `symptomlist` VALUES ( 228007,'Lucio phenomenon');
INSERT INTO `symptomlist` VALUES ( 241006,'Epilepsia partialis continua');
INSERT INTO `symptomlist` VALUES ( 242004,'Noninfectious jejunitis');
INSERT INTO `symptomlist` VALUES ( 253005,'Sycosis');
INSERT INTO `symptomlist` VALUES ( 257006,'Acne rosacea, erythematous telangiectatic type');
INSERT INTO `symptomlist` VALUES ( 264008,'Blind hypertensive eye');
INSERT INTO `symptomlist` VALUES ( 276008,'Poisoning by oxytocin');
INSERT INTO `symptomlist` VALUES ( 279001,'Senile myocarditis');
INSERT INTO `symptomlist` VALUES ( 281004,'Dementia associated with alcoholism');
INSERT INTO `symptomlist` VALUES ( 282006,'Acute myocardial infarction of basal-lateral wall');
INSERT INTO `symptomlist` VALUES ( 290006,'Melnick-Fraser syndrome');
INSERT INTO `symptomlist` VALUES ( 292003,'EEG finding');
INSERT INTO `symptomlist` VALUES ( 297009,'Acute myringitis');
INSERT INTO `symptomlist` VALUES ( 299007,'Paraffinoma of skin');
INSERT INTO `symptomlist` VALUES ( 303002,'Apoplectic pancreatitis');
INSERT INTO `symptomlist` VALUES ( 308006,'Pearly penile papules');
INSERT INTO `symptomlist` VALUES ( 310008,'Boil of penis');
INSERT INTO `symptomlist` VALUES ( 313005,'Déjà vu');
INSERT INTO `symptomlist` VALUES ( 317006,'Reactive hypoglycemia');
INSERT INTO `symptomlist` VALUES ( 320003,'Cervical dilatation, 1cm');
INSERT INTO `symptomlist` VALUES ( 324007,'Plaster ulcer');
INSERT INTO `symptomlist` VALUES ( 330007,'Occipital headache');
INSERT INTO `symptomlist` VALUES ( 335002,'Pylorospasm');
INSERT INTO `symptomlist` VALUES ( 341009,'ABO incompatibility reaction');
INSERT INTO `symptomlist` VALUES ( 349006,'Absent tendon reflex');
INSERT INTO `symptomlist` VALUES ( 355001,'Hemorrhagic shock');
INSERT INTO `symptomlist` VALUES ( 357009,'Closed fracture of trapezoidal bone of wrist');
INSERT INTO `symptomlist` VALUES ( 359007,'Kernicterus due to isoimmunization');
INSERT INTO `symptomlist` VALUES ( 360002,'Acute radiation disease');
INSERT INTO `symptomlist` VALUES ( 364006,'Acute left-sided heart failure');
INSERT INTO `symptomlist` VALUES ( 366008,'Hidromeiosis');
INSERT INTO `symptomlist` VALUES ( 368009,'Heart valve disorder');
INSERT INTO `symptomlist` VALUES ( 369001,'Normal jugular venous pressure');
INSERT INTO `symptomlist` VALUES ( 378007,'Morquio syndrome');
INSERT INTO `symptomlist` VALUES ( 382009,'Legal history finding relating to child');
INSERT INTO `symptomlist` VALUES ( 383004,'Passive range of hip extension - finding');
INSERT INTO `symptomlist` VALUES ( 385006,'Secondary peripheral neuropathy');
INSERT INTO `symptomlist` VALUES ( 387003,'Melanuria');
INSERT INTO `symptomlist` VALUES ( 398002,'Left axis deviation greater than -90 degrees by EKG');
INSERT INTO `symptomlist` VALUES ( 407000,'Congenital hepatomegaly');
INSERT INTO `symptomlist` VALUES ( 408005,'Tooth chattering');
INSERT INTO `symptomlist` VALUES ( 409002,'Food allergy diet');
INSERT INTO `symptomlist` VALUES ( 426008,'Superficial injury of ankle without infection');
INSERT INTO `symptomlist` VALUES ( 431005,'Hypertrophy of scrotum');
INSERT INTO `symptomlist` VALUES ( 437009,'Abnormal composition of urine');
INSERT INTO `symptomlist` VALUES ( 440009,'Persistent hyperphenylalaninemia');
INSERT INTO `symptomlist` VALUES ( 442001,'Secondary hypopituitarism');
INSERT INTO `symptomlist` VALUES ( 443006,'Cystocele affecting pregnancy');
INSERT INTO `symptomlist` VALUES ( 447007,'Coach in sports activity accident');
INSERT INTO `symptomlist` VALUES ( 450005,'Ulcerative stomatitis');
INSERT INTO `symptomlist` VALUES ( 452002,'Blister of groin without infection');
INSERT INTO `symptomlist` VALUES ( 460001,'Squamous metaplasia of prostate gland');
INSERT INTO `symptomlist` VALUES ( 467003,'Old laceration of muscles of pelvic floor');
INSERT INTO `symptomlist` VALUES ( 470004,'Vitreous touch syndrome');
INSERT INTO `symptomlist` VALUES ( 479003,'Graves disease with pretibial myxedema AND with thyrotoxic crisis');
INSERT INTO `symptomlist` VALUES ( 486006,'Acute vascular insufficiency');
INSERT INTO `symptomlist` VALUES ( 488007,'Fibroid myocarditis');
INSERT INTO `symptomlist` VALUES ( 490008,'Upper respiratory tract hypersensitivity reaction');
INSERT INTO `symptomlist` VALUES ( 496002,'Closed traumatic dislocation of third cervical vertebra (disorder)');
INSERT INTO `symptomlist` VALUES ( 504009,'Androgen-dependent hirsutism');
INSERT INTO `symptomlist` VALUES ( 517007,'Foreign body in hypopharynx');
INSERT INTO `symptomlist` VALUES ( 518002,'Multiple aggregation');
INSERT INTO `symptomlist` VALUES ( 520004,'Congenital bent nose');
INSERT INTO `symptomlist` VALUES ( 527001,'Spontaneous fetal evolution, Roederers method');
INSERT INTO `symptomlist` VALUES ( 536002,'Glissonian cirrhosis');
INSERT INTO `symptomlist` VALUES ( 539009,'Conjunctival argyrosis');
INSERT INTO `symptomlist` VALUES ( 547009,'Hypersecretion of calcitonin');
INSERT INTO `symptomlist` VALUES ( 548004,'13p partial trisomy syndrome');
INSERT INTO `symptomlist` VALUES ( 554003,'2p partial trisomy syndrome');
INSERT INTO `symptomlist` VALUES ( 555002,'Dicentra species poisoning');
INSERT INTO `symptomlist` VALUES ( 563001,'Nystagmus');
INSERT INTO `symptomlist` VALUES ( 568005,'Tic disorder');
INSERT INTO `symptomlist` VALUES ( 586008,'Contact dermatitis due to primrose');
INSERT INTO `symptomlist` VALUES ( 590005,'Congenital aneurysm of anterior communicating artery');
INSERT INTO `symptomlist` VALUES ( 596004,'Premenstrual dysphoric disorder');
INSERT INTO `symptomlist` VALUES ( 599006,'Chronic pneumothorax');
INSERT INTO `symptomlist` VALUES ( 600009,'Pyromania');
INSERT INTO `symptomlist` VALUES ( 607007,'Decreased vital capacity');
INSERT INTO `symptomlist` VALUES ( 610000,'Spastic aphonia');
INSERT INTO `symptomlist` VALUES ( 613003,'Fragile X syndrome');
INSERT INTO `symptomlist` VALUES ( 615005,'Obstruction due to foreign body accidentally left in operative wound AND/OR body cavity during a procedure');
INSERT INTO `symptomlist` VALUES ( 616006,'Sensorimotor disorder of eyelid');
INSERT INTO `symptomlist` VALUES ( 626004,'Hypercortisolism due to nonpituitary tumor');
INSERT INTO `symptomlist` VALUES ( 631002,'Transfusion reaction due to minor incompatibility');
INSERT INTO `symptomlist` VALUES ( 640003,'Injury of pneumogastric nerve');
INSERT INTO `symptomlist` VALUES ( 643001,'Hypertrophy of lip');
INSERT INTO `symptomlist` VALUES ( 646009,'Idiopathic cyst of anterior chamber of eye (disorder)');
INSERT INTO `symptomlist` VALUES ( 649002,'Open fracture of distal end of ulna');
INSERT INTO `symptomlist` VALUES ( 651003,'Root work');
INSERT INTO `symptomlist` VALUES ( 652005,'Gangrenous tonsillitis');
INSERT INTO `symptomlist` VALUES ( 655007,'Abnormal fetal heart beat noted before labor in liveborn infant');
INSERT INTO `symptomlist` VALUES ( 658009,'Injury of colon without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 664002,'Delayed ovulation');
INSERT INTO `symptomlist` VALUES ( 666000,'Poisoning by antivaricose drug AND/OR sclerosing agent');
INSERT INTO `symptomlist` VALUES ( 675003,'Torsion of intestine');
INSERT INTO `symptomlist` VALUES ( 682004,'Thrombosis complicating pregnancy AND/OR puerperium');
INSERT INTO `symptomlist` VALUES ( 701003,'Adult osteochondritis of spine');
INSERT INTO `symptomlist` VALUES ( 703000,'Congenital adhesions of tongue');
INSERT INTO `symptomlist` VALUES ( 714002,'Abrasion and/or friction burn of toe with infection (disorder)');
INSERT INTO `symptomlist` VALUES ( 715001,'Nontraumatic rupture of urethra');
INSERT INTO `symptomlist` VALUES ( 718004,'Acute bronchiolitis with obstruction');
INSERT INTO `symptomlist` VALUES ( 733007,'Superficial foreign body of groin without major open wound but with infection');
INSERT INTO `symptomlist` VALUES ( 734001,'Opocephalus');
INSERT INTO `symptomlist` VALUES ( 736004,'Abscess of hip');
INSERT INTO `symptomlist` VALUES ( 750009,'Schistosoma mansoni infection (disorder)');
INSERT INTO `symptomlist` VALUES ( 755004,'Postgastrectomy phytobezoar');
INSERT INTO `symptomlist` VALUES ( 756003,'Chronic rheumatic myopericarditis');
INSERT INTO `symptomlist` VALUES ( 758002,'Cyst of uterus');
INSERT INTO `symptomlist` VALUES ( 775008,'Open wound of head with complication');
INSERT INTO `symptomlist` VALUES ( 776009,'Partial arterial retinal occlusion');
INSERT INTO `symptomlist` VALUES ( 781000,'Cestrum diurnum poisoning');
INSERT INTO `symptomlist` VALUES ( 786005,'Clinical stage I B');
INSERT INTO `symptomlist` VALUES ( 787001,'Rheumatic mitral stenosis with regurgitation');
INSERT INTO `symptomlist` VALUES ( 788006,'Disease-related diet');
INSERT INTO `symptomlist` VALUES ( 792004,'Jakob-Creutzfeldt disease');
INSERT INTO `symptomlist` VALUES ( 799008,'Sigmoid colon ulcer');
INSERT INTO `symptomlist` VALUES ( 801006,'Nonvenomous insect bite of foot with infection');
INSERT INTO `symptomlist` VALUES ( 805002,'Pneumoconiosis due to silica');
INSERT INTO `symptomlist` VALUES ( 811004,'Flail motion');
INSERT INTO `symptomlist` VALUES ( 813001,'Ankle instability');
INSERT INTO `symptomlist` VALUES ( 815008,'Episcleritis');
INSERT INTO `symptomlist` VALUES ( 816009,'Genetic recombination');
INSERT INTO `symptomlist` VALUES ( 818005,'Third degree burn of multiple sites of lower limb');
INSERT INTO `symptomlist` VALUES ( 825003,'Superficial injury of axilla with infection');
INSERT INTO `symptomlist` VALUES ( 827006,'Late congenital syphilis, latent (+ sero, - CSF, 2 years OR more)');
INSERT INTO `symptomlist` VALUES ( 832007,'Moderate major depression');
INSERT INTO `symptomlist` VALUES ( 834008,'Chair-seated facing coital position');
INSERT INTO `symptomlist` VALUES ( 841002,'Congenital absence of skull bone');
INSERT INTO `symptomlist` VALUES ( 842009,'Consanguinity');
INSERT INTO `symptomlist` VALUES ( 843004,'Poliomyelomalacia');
INSERT INTO `symptomlist` VALUES ( 844005,'Behavior finding');
INSERT INTO `symptomlist` VALUES ( 845006,'Injury of inferior mesenteric artery');
INSERT INTO `symptomlist` VALUES ( 849000,'Total cataract');
INSERT INTO `symptomlist` VALUES ( 857002,'Erythema simplex');
INSERT INTO `symptomlist` VALUES ( 862001,'Anemia caused by chlorate (disorder)');
INSERT INTO `symptomlist` VALUES ( 865004,'Hyperalimentation formula for ileus');
INSERT INTO `symptomlist` VALUES ( 871005,'Contracted pelvis');
INSERT INTO `symptomlist` VALUES ( 874002,'Therapeutic diuresis');
INSERT INTO `symptomlist` VALUES ( 875001,'Chalcosis of eye');
INSERT INTO `symptomlist` VALUES ( 888003,'Foetal or neonatal effect of maternal blood loss');
INSERT INTO `symptomlist` VALUES ( 890002,'Deep third degree burn of elbow');
INSERT INTO `symptomlist` VALUES ( 899001,'Axis I diagnosis');
INSERT INTO `symptomlist` VALUES ( 903008,'Chorioretinal infarction');
INSERT INTO `symptomlist` VALUES ( 904002,'Pinards sign');
INSERT INTO `symptomlist` VALUES ( 908004,'Superficial injury of interscapular region without infection');
INSERT INTO `symptomlist` VALUES ( 919001,'Pseudohomosexual state');
INSERT INTO `symptomlist` VALUES ( 928000,'Disorder of musculoskeletal system');
INSERT INTO `symptomlist` VALUES ( 931004,'Gestation period, 9 weeks');
INSERT INTO `symptomlist` VALUES ( 932006,'Flat affect');
INSERT INTO `symptomlist` VALUES ( 934007,'Thalassemia intermedia');
INSERT INTO `symptomlist` VALUES ( 943003,'Congenital retinal aneurysm');
INSERT INTO `symptomlist` VALUES ( 961007,'Erythema nodosum, acute form');
INSERT INTO `symptomlist` VALUES ( 962000,'Disability evaluation, disability 6%');
INSERT INTO `symptomlist` VALUES ( 964004,'Open wound of pharynx without complication');
INSERT INTO `symptomlist` VALUES ( 965003,'Toxic amblyopia');
INSERT INTO `symptomlist` VALUES ( 975000,'Anorectal agenesis');
INSERT INTO `symptomlist` VALUES ( 978003,'Chronic infantile eczema');
INSERT INTO `symptomlist` VALUES ( 981008,'Hemorrhagic proctitis');
INSERT INTO `symptomlist` VALUES ( 984000,'Perirectal cellulitis');
INSERT INTO `symptomlist` VALUES ( 987007,'Cellulitis of temple region');
INSERT INTO `symptomlist` VALUES ( 991002,'Wide QRS complex');
INSERT INTO `symptomlist` VALUES ( 998008,'Chagas disease with heart involvement');
INSERT INTO `symptomlist` VALUES ( 1003002,'Religious discrimination');
INSERT INTO `symptomlist` VALUES ( 1020003,'Disease due to Nairovirus');
INSERT INTO `symptomlist` VALUES ( 1023001,'Apnea');
INSERT INTO `symptomlist` VALUES ( 1027000,'Alkaline reflux disease');
INSERT INTO `symptomlist` VALUES ( 1031006,'Open wound of trachea without complication');
INSERT INTO `symptomlist` VALUES ( 1033009,'Thoracic arthritis');
INSERT INTO `symptomlist` VALUES ( 1034003,'Mesenteric-portal fistula');
INSERT INTO `symptomlist` VALUES ( 1038000,'Disacchariduria');
INSERT INTO `symptomlist` VALUES ( 1045000,'Colonospasm');
INSERT INTO `symptomlist` VALUES ( 1046004,'Ureteritis glandularis');
INSERT INTO `symptomlist` VALUES ( 1051005,'Hyperplasia of islet alpha cells with gastrin excess');
INSERT INTO `symptomlist` VALUES ( 1055001,'Stenosis of precerebral artery');
INSERT INTO `symptomlist` VALUES ( 1059007,'Opisthorchiasis');
INSERT INTO `symptomlist` VALUES ( 1070000,'Facial myokymia');
INSERT INTO `symptomlist` VALUES ( 1073003,'Xeroderma pigmentosum, group B');
INSERT INTO `symptomlist` VALUES ( 1074009,'Glucocorticoid-responsive primary aldosteronism');
INSERT INTO `symptomlist` VALUES ( 1077002,'Septal infarction by EKG');
INSERT INTO `symptomlist` VALUES ( 1079004,'Macular retinal cyst');
INSERT INTO `symptomlist` VALUES ( 1085006,'Candidiasis of vulva');
INSERT INTO `symptomlist` VALUES ( 1089000,'Intrauterine sepsis of fetus');
INSERT INTO `symptomlist` VALUES ( 1102005,'Intraerythrocytic parasitosis by Nuttallia');
INSERT INTO `symptomlist` VALUES ( 1107004,'Early latent syphilis, positive serology, negative cerebrospinal fluid, with relapse after treatment (disorder)');
INSERT INTO `symptomlist` VALUES ( 1108009,'Female pattern alopecia');
INSERT INTO `symptomlist` VALUES ( 1111005,'Normal sebaceous gland activity');
INSERT INTO `symptomlist` VALUES ( 1112003,'Degenerative disorder of eyelid');
INSERT INTO `symptomlist` VALUES ( 1116000,'Chronic aggressive type B viral hepatitis');
INSERT INTO `symptomlist` VALUES ( 1124005,'Postpartum period, 6 days');
INSERT INTO `symptomlist` VALUES ( 1125006,'Septicemia during labor');
INSERT INTO `symptomlist` VALUES ( 1126007,'Knee locking');
INSERT INTO `symptomlist` VALUES ( 1131009,'Congenital valvular insufficiency');
INSERT INTO `symptomlist` VALUES ( 1134001,'Muehrckes lines');
INSERT INTO `symptomlist` VALUES ( 1135000,'Solar retinopathy');
INSERT INTO `symptomlist` VALUES ( 1139006,'Confrontation (visual) test');
INSERT INTO `symptomlist` VALUES ( 1140008,'Thermal hypesthesia');
INSERT INTO `symptomlist` VALUES ( 1141007,'Circumoral paresthesia');
INSERT INTO `symptomlist` VALUES ( 1145003,'Developmental speech disorder');
INSERT INTO `symptomlist` VALUES ( 1150009,'Congenital microcheilia');
INSERT INTO `symptomlist` VALUES ( 1151008,'Generalized constriction of visual field');
INSERT INTO `symptomlist` VALUES ( 1152001,'Skin reaction negative');
INSERT INTO `symptomlist` VALUES ( 1155004,'EKG hypertrophy');
INSERT INTO `symptomlist` VALUES ( 1168007,'Allotype');
INSERT INTO `symptomlist` VALUES ( 1184008,'Glasgow coma scale, 10');
INSERT INTO `symptomlist` VALUES ( 1194003,'Disease condition determination, well controlled');
INSERT INTO `symptomlist` VALUES ( 1196001,'Chronic bipolar II disorder, most recent episode major depressive');
INSERT INTO `symptomlist` VALUES ( 1197005,'Carbuncle of heel');
INSERT INTO `symptomlist` VALUES ( 1201005,'Benign essential hypertension');
INSERT INTO `symptomlist` VALUES ( 1207009,'Glaucomatous atrophy of optic disc');
INSERT INTO `symptomlist` VALUES ( 1208004,'Gastroptosis');
INSERT INTO `symptomlist` VALUES ( 1212005,'Childhood type dermatomyositis');
INSERT INTO `symptomlist` VALUES ( 1214006,'Infection by Strongyloides');
INSERT INTO `symptomlist` VALUES ( 1232006,'Congenital articular rigidity with myopathy');
INSERT INTO `symptomlist` VALUES ( 1239002,'Congenital anteversion of femur');
INSERT INTO `symptomlist` VALUES ( 1240000,'Prone body position');
INSERT INTO `symptomlist` VALUES ( 1259003,'Schistosis');
INSERT INTO `symptomlist` VALUES ( 1261007,'Fracture of multiple ribs');
INSERT INTO `symptomlist` VALUES ( 1264004,'Injury of descending left colon without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 1271009,'Knuckle pads, deafness AND leukonychia syndrome');
INSERT INTO `symptomlist` VALUES ( 1280009,'Isologous chimera');
INSERT INTO `symptomlist` VALUES ( 1282001,'Perichondritis of larynx');
INSERT INTO `symptomlist` VALUES ( 1284000,'Abnormal jaw closure');
INSERT INTO `symptomlist` VALUES ( 1286003,'Vitamin K deficiency coagulation disorder');
INSERT INTO `symptomlist` VALUES ( 1287007,'Congenital absence of bile duct');
INSERT INTO `symptomlist` VALUES ( 1297003,'Infection by Cladosporium carrionii');
INSERT INTO `symptomlist` VALUES ( 1308001,'Complication of reimplant');
INSERT INTO `symptomlist` VALUES ( 1310004,'Impaired glucose tolerance associated with genetic syndrome');
INSERT INTO `symptomlist` VALUES ( 1317001,'Injury of ovary without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 1318006,'Post-translational genetic protein processing');
INSERT INTO `symptomlist` VALUES ( 1323006,'Poisoning by kanamycin');
INSERT INTO `symptomlist` VALUES ( 1332008,'Conjugated visual deviation');
INSERT INTO `symptomlist` VALUES ( 1335005,'Induratio penis plastica');
INSERT INTO `symptomlist` VALUES ( 1343000,'Deep transverse arrest');
INSERT INTO `symptomlist` VALUES ( 1345007,'Hang nail');
INSERT INTO `symptomlist` VALUES ( 1351002,'Injury of iliac artery');
INSERT INTO `symptomlist` VALUES ( 1356007,'Calculus of common duct with obstruction');
INSERT INTO `symptomlist` VALUES ( 1361009,'Leukocoria');
INSERT INTO `symptomlist` VALUES ( 1363007,'Fetal or neonatal effect of chronic maternal respiratory disease (disorder)');
INSERT INTO `symptomlist` VALUES ( 1367008,'Injury of superior mesenteric artery');
INSERT INTO `symptomlist` VALUES ( 1370007,'Open fracture of metacarpal bone');
INSERT INTO `symptomlist` VALUES ( 1372004,'Uterus unicornis');
INSERT INTO `symptomlist` VALUES ( 1376001,'Obsessive compulsive personality disorder');
INSERT INTO `symptomlist` VALUES ( 1378000,'Supination-eversion injury of ankle');
INSERT INTO `symptomlist` VALUES ( 1380006,'Agoraphobia without history of panic disorder with limited symptom attacks');
INSERT INTO `symptomlist` VALUES ( 1383008,'Hallucinogen mood disorder');
INSERT INTO `symptomlist` VALUES ( 1384002,'Diffuse cholesteatosis of middle ear');
INSERT INTO `symptomlist` VALUES ( 1386000,'Intracranial hemorrhage');
INSERT INTO `symptomlist` VALUES ( 1387009,'Solanum nigrum poisoning');
INSERT INTO `symptomlist` VALUES ( 1388004,'Metabolic alkalosis');
INSERT INTO `symptomlist` VALUES ( 1393001,'Lenz-Majewski hyperostosis syndrome');
INSERT INTO `symptomlist` VALUES ( 1395008,'Complication of ultrasound therapy');
INSERT INTO `symptomlist` VALUES ( 1402001,'Fear (finding)');
INSERT INTO `symptomlist` VALUES ( 1412008,'Anterior subcapsular polar cataract');
INSERT INTO `symptomlist` VALUES ( 1415005,'Lymphangitis');
INSERT INTO `symptomlist` VALUES ( 1418007,'Hypoplastic chondrodystrophy');
INSERT INTO `symptomlist` VALUES ( 1419004,'Injury of prostate without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 1426004,'Necrotizing glomerulonephritis');
INSERT INTO `symptomlist` VALUES ( 1447000,'Icthyoparasitism');
INSERT INTO `symptomlist` VALUES ( 1469007,'Spontaneous abortion with urinary tract infection');
INSERT INTO `symptomlist` VALUES ( 1474004,'Hypertensive heart AND renal disease complicating AND/OR reason for care during childbirth');
INSERT INTO `symptomlist` VALUES ( 1475003,'Herpes labialis');
INSERT INTO `symptomlist` VALUES ( 1478001,'Obliteration of lymphatic vessel');
INSERT INTO `symptomlist` VALUES ( 1479009,'20q partial trisomy syndrome');
INSERT INTO `symptomlist` VALUES ( 1482004,'Chalazion');
INSERT INTO `symptomlist` VALUES ( 1486001,'Orbital congestion');
INSERT INTO `symptomlist` VALUES ( 1488000,'Postoperative nausea and vomiting');
INSERT INTO `symptomlist` VALUES ( 1489008,'Hordeolum externum');
INSERT INTO `symptomlist` VALUES ( 1492007,'Congenital anomaly of large intestine');
INSERT INTO `symptomlist` VALUES ( 1493002,'Acute endophthalmitis');
INSERT INTO `symptomlist` VALUES ( 1499003,'Bipolar I disorder, single manic episode with postpartum onset');
INSERT INTO `symptomlist` VALUES ( 1512006,'Congenital stricture of bile duct');
INSERT INTO `symptomlist` VALUES ( 1515008,'Gorhams disease');
INSERT INTO `symptomlist` VALUES ( 1518005,'Splenitis');
INSERT INTO `symptomlist` VALUES ( 1519002,'Congenital phlebectasia');
INSERT INTO `symptomlist` VALUES ( 1521007,'Blister of buttock without infection');
INSERT INTO `symptomlist` VALUES ( 1523005,'Clinical stage IV B');
INSERT INTO `symptomlist` VALUES ( 1525003,'Blister of foot without infection');
INSERT INTO `symptomlist` VALUES ( 1531000,'Poisoning by nitrofuran derivatives');
INSERT INTO `symptomlist` VALUES ( 1532007,'Viral pharyngitis');
INSERT INTO `symptomlist` VALUES ( 1534008,'Palsy of conjugate gaze');
INSERT INTO `symptomlist` VALUES ( 1538006,'Central nervous system malformation in fetus affecting obstetrical care');
INSERT INTO `symptomlist` VALUES ( 1539003,'Acquired trigger finger');
INSERT INTO `symptomlist` VALUES ( 1542009,'Omphalocele with obstruction');
INSERT INTO `symptomlist` VALUES ( 1544005,'Open dislocation of knee');
INSERT INTO `symptomlist` VALUES ( 1551001,'Osteomyelitis of femur (disorder)');
INSERT INTO `symptomlist` VALUES ( 1556006,'Clark melanoma level 4');
INSERT INTO `symptomlist` VALUES ( 1563006,'Protein S deficiency disease');
INSERT INTO `symptomlist` VALUES ( 1567007,'Chronic gastric ulcer without hemorrhage, without perforation AND without obstruction');
INSERT INTO `symptomlist` VALUES ( 1588003,'Heterosexual precocious puberty');
INSERT INTO `symptomlist` VALUES ( 1592005,'Failed attempted abortion with uremia');
INSERT INTO `symptomlist` VALUES ( 1593000,'Infantile hemiplegia');
INSERT INTO `symptomlist` VALUES ( 1606009,'Infection by Macracanthorhynchus hirudinaceus');
INSERT INTO `symptomlist` VALUES ( 1608005,'Increased capillary permeability');
INSERT INTO `symptomlist` VALUES ( 1639007,'Abnormality of organs AND/OR soft tissues of pelvis affecting pregnancy');
INSERT INTO `symptomlist` VALUES ( 1647007,'Poisoning by primaquine');
INSERT INTO `symptomlist` VALUES ( 1648002,'Lymphocytic pseudotumor of lung');
INSERT INTO `symptomlist` VALUES ( 1654001,'Corticosteroid-induced glaucoma');
INSERT INTO `symptomlist` VALUES ( 1657008,'Mevinphos poisoning');
INSERT INTO `symptomlist` VALUES ( 1658003,'Closed fracture of acromial end of clavicle');
INSERT INTO `symptomlist` VALUES ( 1663004,'G2 stage');
INSERT INTO `symptomlist` VALUES ( 1667003,'Early fontanel closure');
INSERT INTO `symptomlist` VALUES ( 1670004,'Cerebral hemiparesis');
INSERT INTO `symptomlist` VALUES ( 1671000,'Sago spleen');
INSERT INTO `symptomlist` VALUES ( 1674008,'Juvenile epithelial corneal dystrophy');
INSERT INTO `symptomlist` VALUES ( 1679003,'Arthritis associated with another disorder');
INSERT INTO `symptomlist` VALUES ( 1682008,'Transitory amino acid metabolic disorder');
INSERT INTO `symptomlist` VALUES ( 1685005,'Rat bite fever');
INSERT INTO `symptomlist` VALUES ( 1686006,'Sedative, hypnotic AND/OR anxiolytic-induced anxiety disorder');
INSERT INTO `symptomlist` VALUES ( 1694004,'Accessory lobe of lung');
INSERT INTO `symptomlist` VALUES ( 1698001,'Ulcer of bile duct');
INSERT INTO `symptomlist` VALUES ( 1703007,'Increased leg circumference');
INSERT INTO `symptomlist` VALUES ( 1705000,'Closed fracture of base of neck of femur');
INSERT INTO `symptomlist` VALUES ( 1708003,'Open dislocation of clavicle');
INSERT INTO `symptomlist` VALUES ( 1714005,'Photokeratitis');
INSERT INTO `symptomlist` VALUES ( 1717003,'Idiopathic guttate hypomelanosis');
INSERT INTO `symptomlist` VALUES ( 1723008,'Urethral stricture due to schistosomiasis');
INSERT INTO `symptomlist` VALUES ( 1724002,'Infection by Crenosoma');
INSERT INTO `symptomlist` VALUES ( 1734006,'Fracture of vertebral column with spinal cord injury');
INSERT INTO `symptomlist` VALUES ( 1735007,'Thrill');
INSERT INTO `symptomlist` VALUES ( 1739001,'Fracture of occipital bone');
INSERT INTO `symptomlist` VALUES ( 1742007,'Female hypererotism');
INSERT INTO `symptomlist` VALUES ( 1744008,'Fusion of teeth');
INSERT INTO `symptomlist` VALUES ( 1748006,'Thrombophlebitis of deep femoral vein');
INSERT INTO `symptomlist` VALUES ( 1755008,'Old myocardial infarction');
INSERT INTO `symptomlist` VALUES ( 1761006,'Biliary cirrhosis');
INSERT INTO `symptomlist` VALUES ( 1763009,'Interstitial keratitis');
INSERT INTO `symptomlist` VALUES ( 1767005,'Fishers syndrome');
INSERT INTO `symptomlist` VALUES ( 1769008,'Thoracodidymus');
INSERT INTO `symptomlist` VALUES ( 1771008,'Insulin biosynthesis defect');
INSERT INTO `symptomlist` VALUES ( 1776003,'Renal tubular acidosis');
INSERT INTO `symptomlist` VALUES ( 1777007,'Increased molecular dissociation');
INSERT INTO `symptomlist` VALUES ( 1778002,'Malocclusion due to abnormal swallowing');
INSERT INTO `symptomlist` VALUES ( 1779005,'Mohr syndrome');
INSERT INTO `symptomlist` VALUES ( 1794009,'Idiopathic corneal edema');
INSERT INTO `symptomlist` VALUES ( 1816003,'Panic disorder with agoraphobia, severe agoraphobic avoidance AND mild panic attacks');
INSERT INTO `symptomlist` VALUES ( 1821000,'Chemoreceptor apnea');
INSERT INTO `symptomlist` VALUES ( 1822007,'Impaired glucose tolerance associated with pancreatic disease');
INSERT INTO `symptomlist` VALUES ( 1824008,'Allergic gastritis');
INSERT INTO `symptomlist` VALUES ( 1826005,'Granuloma of lip');
INSERT INTO `symptomlist` VALUES ( 1828006,'Infestation by Gasterophilus haemorrhoidalis');
INSERT INTO `symptomlist` VALUES ( 1829003,'Microcephalus');
INSERT INTO `symptomlist` VALUES ( 1833005,'Phacoanaphylactic endophthalmitis');
INSERT INTO `symptomlist` VALUES ( 1835003,'Necrosis of pancreas');
INSERT INTO `symptomlist` VALUES ( 1837006,'Poisoning by metaproterenol');
INSERT INTO `symptomlist` VALUES ( 1845001,'Paraparesis');
INSERT INTO `symptomlist` VALUES ( 1847009,'Endophthalmitis');
INSERT INTO `symptomlist` VALUES ( 1848004,'Poisoning by gaseous anesthetic');
INSERT INTO `symptomlist` VALUES ( 1852004,'Traumatic injury of sixth cranial nerve');
INSERT INTO `symptomlist` VALUES ( 1855002,'Developmental academic disorder');
INSERT INTO `symptomlist` VALUES ( 1856001,'Accessory nose');
INSERT INTO `symptomlist` VALUES ( 1857005,'Gestational rubella syndrome');
INSERT INTO `symptomlist` VALUES ( 1860003,'Fluid volume disorder');
INSERT INTO `symptomlist` VALUES ( 1865008,'Impaired intestinal protein absorption');
INSERT INTO `symptomlist` VALUES ( 1869002,'Rupture of sphincter of pupil');
INSERT INTO `symptomlist` VALUES ( 1881003,'Increased nutritional requirement');
INSERT INTO `symptomlist` VALUES ( 1892002,'Star figure at the macula');
INSERT INTO `symptomlist` VALUES ( 1896004,'Ectopic breast tissue');
INSERT INTO `symptomlist` VALUES ( 1897008,'Amsinckia species poisoning');
INSERT INTO `symptomlist` VALUES ( 1899006,'Autosomal hereditary disorder');
INSERT INTO `symptomlist` VALUES ( 1903004,'Infestation by Psorergates ovis');
INSERT INTO `symptomlist` VALUES ( 1908008,'von Willebrand disease, type IIC');
INSERT INTO `symptomlist` VALUES ( 1909000,'Impairment level: better eye: severe impairment: lesser eye: near-total impairment');
INSERT INTO `symptomlist` VALUES ( 1922008,'Congenital absence of urethra');
INSERT INTO `symptomlist` VALUES ( 1926006,'Osteopetrosis');
INSERT INTO `symptomlist` VALUES ( 1939005,'Abnormal vascular flow');
INSERT INTO `symptomlist` VALUES ( 1943009,'Left-right confusion');
INSERT INTO `symptomlist` VALUES ( 1953005,'Congenital deficiency of pigment of skin');
INSERT INTO `symptomlist` VALUES ( 1954004,'Dilated cardiomyopathy secondary to toxic reaction');
INSERT INTO `symptomlist` VALUES ( 1955003,'Preauricular dimple');
INSERT INTO `symptomlist` VALUES ( 1959009,'Encephalartos species poisoning');
INSERT INTO `symptomlist` VALUES ( 1961000,'Chronic polyarticular juvenile rheumatoid arthritis');
INSERT INTO `symptomlist` VALUES ( 1963002,'Paroxysmal nocturnal hemoglobinuria');
INSERT INTO `symptomlist` VALUES ( 1965009,'Normal skin pH');
INSERT INTO `symptomlist` VALUES ( 1967001,'Longitudinal absence of radius AND ulna');
INSERT INTO `symptomlist` VALUES ( 1973000,'Sedative, hypnotic AND/OR anxiolytic-induced psychotic disorder with delusions');
INSERT INTO `symptomlist` VALUES ( 1977004,'Poisoning by oxymetholone');
INSERT INTO `symptomlist` VALUES ( 1979001,'Focal choroiditis');
INSERT INTO `symptomlist` VALUES ( 1980003,'Seromucinous otitis media');
INSERT INTO `symptomlist` VALUES ( 1981004,'Urhidrosis');
INSERT INTO `symptomlist` VALUES ( 1989002,'Burn of vagina AND/OR uterus');
INSERT INTO `symptomlist` VALUES ( 2004005,'Normal blood pressure');
INSERT INTO `symptomlist` VALUES ( 2012002,'Fracture of lunate bone of wrist');
INSERT INTO `symptomlist` VALUES ( 2024009,'Dilated cardiomyopathy secondary to metazoal myocarditis');
INSERT INTO `symptomlist` VALUES ( 2028007,'Erythema induratum');
INSERT INTO `symptomlist` VALUES ( 2032001,'Cerebral edema');
INSERT INTO `symptomlist` VALUES ( 2036003,'Acquired factor VII deficiency disease');
INSERT INTO `symptomlist` VALUES ( 2040007,'Neurogenic thoracic outlet syndrome');
INSERT INTO `symptomlist` VALUES ( 2041006,'Eunuchoid gigantism');
INSERT INTO `symptomlist` VALUES ( 2043009,'Alcoholic gastritis');
INSERT INTO `symptomlist` VALUES ( 2055003,'Recurrent erosion of cornea');
INSERT INTO `symptomlist` VALUES ( 2058001,'Bilateral loss of labyrinthine reactivity');
INSERT INTO `symptomlist` VALUES ( 2061000,'Conductive hearing loss of combined sites');
INSERT INTO `symptomlist` VALUES ( 2065009,'Dominant hereditary optic atrophy');
INSERT INTO `symptomlist` VALUES ( 2066005,'Gastric ulcer with hemorrhage AND perforation but without obstruction');
INSERT INTO `symptomlist` VALUES ( 2070002,'Burning sensation in eye');
INSERT INTO `symptomlist` VALUES ( 2073000,'Delusions');
INSERT INTO `symptomlist` VALUES ( 2087000,'Pulmonary nocardiosis');
INSERT INTO `symptomlist` VALUES ( 2089002,'Osteitis deformans');
INSERT INTO `symptomlist` VALUES ( 2091005,'Pharyngeal diverticulitis');
INSERT INTO `symptomlist` VALUES ( 2094002,'Toxic effect of carbon disulfide');
INSERT INTO `symptomlist` VALUES ( 2102007,'Deep vascularization of cornea');
INSERT INTO `symptomlist` VALUES ( 2107001,'Anisomelia');
INSERT INTO `symptomlist` VALUES ( 2109003,'Isolated somatotropin deficiency');
INSERT INTO `symptomlist` VALUES ( 2114004,'Infection by Cysticercus pisiformis');
INSERT INTO `symptomlist` VALUES ( 2116002,'Intramembranous bone formation');
INSERT INTO `symptomlist` VALUES ( 2120003,'Weak cry');
INSERT INTO `symptomlist` VALUES ( 2121004,'Poisoning by ethopropazine');
INSERT INTO `symptomlist` VALUES ( 2128005,'Disease of pharyngeal tonsil');
INSERT INTO `symptomlist` VALUES ( 2129002,'Edema of pharynx');
INSERT INTO `symptomlist` VALUES ( 2132004,'Meconium in amniotic fluid noted before labor in liveborn infant');
INSERT INTO `symptomlist` VALUES ( 2134003,'Diffuse pain');
INSERT INTO `symptomlist` VALUES ( 2136001,'Open wound of jaw with complication');
INSERT INTO `symptomlist` VALUES ( 2138000,'LSP - Left sacroposterior position');
INSERT INTO `symptomlist` VALUES ( 2145000,'Anal intercourse');
INSERT INTO `symptomlist` VALUES ( 2149006,'Decreased hormone production');
INSERT INTO `symptomlist` VALUES ( 2158004,'Infection by Contracaecum');
INSERT INTO `symptomlist` VALUES ( 2167004,'Retinal hemangioblastomatosis');
INSERT INTO `symptomlist` VALUES ( 2169001,'Thoracic radiculitis');
INSERT INTO `symptomlist` VALUES ( 2170000,'Gallop rhythm');
INSERT INTO `symptomlist` VALUES ( 2176006,'Halogen acne');
INSERT INTO `symptomlist` VALUES ( 2177002,'Postherpetic neuralgia');
INSERT INTO `symptomlist` VALUES ( 2186007,'Compensated metabolic alkalosis');
INSERT INTO `symptomlist` VALUES ( 2198002,'Visceral epilepsy');
INSERT INTO `symptomlist` VALUES ( 2202000,'Open posterior dislocation of distal end of femur');
INSERT INTO `symptomlist` VALUES ( 2204004,'Acquired deformity of pinna');
INSERT INTO `symptomlist` VALUES ( 2213002,'Congenital anomaly of vena cava');
INSERT INTO `symptomlist` VALUES ( 2216005,'Nocturnal emission');
INSERT INTO `symptomlist` VALUES ( 2217001,'Superficial injury of perineum without infection');
INSERT INTO `symptomlist` VALUES ( 2219003,'Disability evaluation, disability 100%');
INSERT INTO `symptomlist` VALUES ( 2224000,'Selenium poisoning');
INSERT INTO `symptomlist` VALUES ( 2228002,'Scintillating scotoma');
INSERT INTO `symptomlist` VALUES ( 2229005,'Chimera');
INSERT INTO `symptomlist` VALUES ( 2231001,'Nerve plexus disorder');
INSERT INTO `symptomlist` VALUES ( 2237002,'Pleurodynia');
INSERT INTO `symptomlist` VALUES ( 2239004,'Previous pregnancies 6');
INSERT INTO `symptomlist` VALUES ( 2241003,'X-linked absence of thyroxine-binding globulin');
INSERT INTO `symptomlist` VALUES ( 2243000,'Hypercalcemia due to hyperthyroidism');
INSERT INTO `symptomlist` VALUES ( 2245007,'Foreign body in nasopharynx');
INSERT INTO `symptomlist` VALUES ( 2251002,'Primary hypotony of eye');
INSERT INTO `symptomlist` VALUES ( 2256007,'Monozygotic twins');
INSERT INTO `symptomlist` VALUES ( 2261009,'Obstetrical pulmonary fat embolism');
INSERT INTO `symptomlist` VALUES ( 2268003,'Victim of homosexual aggression (finding)');
INSERT INTO `symptomlist` VALUES ( 2284002,'Pulsating exophthalmos');
INSERT INTO `symptomlist` VALUES ( 2295008,'Closed fracture of upper end of forearm');
INSERT INTO `symptomlist` VALUES ( 2296009,'Iron dextran toxicity');
INSERT INTO `symptomlist` VALUES ( 2301009,'Psychosomatic factor in physical condition, psychological component of unknown degree');
INSERT INTO `symptomlist` VALUES ( 2303007,'Inguinal hernia with gangrene');
INSERT INTO `symptomlist` VALUES ( 2304001,'Discitis');
INSERT INTO `symptomlist` VALUES ( 2307008,'Fat necrosis of pancreas');
INSERT INTO `symptomlist` VALUES ( 2308003,'Silent alleles');
INSERT INTO `symptomlist` VALUES ( 2312009,'Reactive attachment disorder of infancy OR early childhood, inhibited type');
INSERT INTO `symptomlist` VALUES ( 2314005,'Unprotected sexual intercourse');
INSERT INTO `symptomlist` VALUES ( 2326000,'Marriage annulment');
INSERT INTO `symptomlist` VALUES ( 2339001,'Sexual overexposure');
INSERT INTO `symptomlist` VALUES ( 2341000,'Infection by Moniliformis');
INSERT INTO `symptomlist` VALUES ( 2351004,'Genetic transduction');
INSERT INTO `symptomlist` VALUES ( 2355008,'Ruds syndrome');
INSERT INTO `symptomlist` VALUES ( 2359002,'Hyper-beta-alaninemia');
INSERT INTO `symptomlist` VALUES ( 2365002,'Chronic granular pharyngitis');
INSERT INTO `symptomlist` VALUES ( 2366001,'Late effect of dislocation');
INSERT INTO `symptomlist` VALUES ( 2367005,'Acute hemorrhagic gastritis');
INSERT INTO `symptomlist` VALUES ( 2374000,'Monofascicular block');
INSERT INTO `symptomlist` VALUES ( 2385003,'Cellulitis of pectoral region');
INSERT INTO `symptomlist` VALUES ( 2388001,'Normal variation in translucency');
INSERT INTO `symptomlist` VALUES ( 2390000,'Acute gonococcal vulvovaginitis');
INSERT INTO `symptomlist` VALUES ( 2391001,'Achondrogenesis');
INSERT INTO `symptomlist` VALUES ( 2396006,'Malignant pyoderma');
INSERT INTO `symptomlist` VALUES ( 2398007,'Quinidine toxicity by EKG');
INSERT INTO `symptomlist` VALUES ( 2403008,'Psychoactive substance dependence');
INSERT INTO `symptomlist` VALUES ( 2415007,'Lumbosacral root lesion');
INSERT INTO `symptomlist` VALUES ( 2418009,'Toxic effect of polyester fumes');
INSERT INTO `symptomlist` VALUES ( 2419001,'Open wound of forehead with complication');
INSERT INTO `symptomlist` VALUES ( 2420007,'Third degree burn of multiple sites of upper limb');
INSERT INTO `symptomlist` VALUES ( 2432006,'Cerebrospinal fluid circulation disorder');
INSERT INTO `symptomlist` VALUES ( 2435008,'Ascariasis');
INSERT INTO `symptomlist` VALUES ( 2437000,'Placenta circumvallata');
INSERT INTO `symptomlist` VALUES ( 2438005,'Iniencephaly');
INSERT INTO `symptomlist` VALUES ( 2439002,'Purulent endocarditis');
INSERT INTO `symptomlist` VALUES ( 2443003,'Hydrogen sulfide poisoning');
INSERT INTO `symptomlist` VALUES ( 2452007,'Fetal rotation');
INSERT INTO `symptomlist` VALUES ( 2463005,'Acquired heterochromia of iris');
INSERT INTO `symptomlist` VALUES ( 2469009,'Onychomalacia');
INSERT INTO `symptomlist` VALUES ( 2471009,'Postoperative intra-abdominal abscess');
INSERT INTO `symptomlist` VALUES ( 2472002,'Anuria');
INSERT INTO `symptomlist` VALUES ( 2473007,'Intermittent vertical heterotropia');
INSERT INTO `symptomlist` VALUES ( 2477008,'Superficial thrombophlebitis');
INSERT INTO `symptomlist` VALUES ( 2492009,'Nutritional disorder');
INSERT INTO `symptomlist` VALUES ( 2495006,'Congenital cerebral arteriovenous aneurysm');
INSERT INTO `symptomlist` VALUES ( 2496007,'Acalculia');
INSERT INTO `symptomlist` VALUES ( 2506003,'Early onset dysthymia');
INSERT INTO `symptomlist` VALUES ( 2513003,'Tinea capitis due to Trichophyton');
INSERT INTO `symptomlist` VALUES ( 2518007,'Cryptogenic sexual precocity');
INSERT INTO `symptomlist` VALUES ( 2521009,'Bone conduction better than air');
INSERT INTO `symptomlist` VALUES ( 2523007,'Salmonella pneumonia');
INSERT INTO `symptomlist` VALUES ( 2526004,'Noninflammatory disorder of the female genital organs');
INSERT INTO `symptomlist` VALUES ( 2528003,'Viremia');
INSERT INTO `symptomlist` VALUES ( 2532009,'Choroidal rupture');
INSERT INTO `symptomlist` VALUES ( 2534005,'Congenital absence of vena cava');
INSERT INTO `symptomlist` VALUES ( 2538008,'Ketosis');
INSERT INTO `symptomlist` VALUES ( 2541004,'Compulsive buying');
INSERT INTO `symptomlist` VALUES ( 2554006,'Acute purulent pericarditis');
INSERT INTO `symptomlist` VALUES ( 2556008,'Periodontal disease');
INSERT INTO `symptomlist` VALUES ( 2560006,'Syndactyly of fingers with fusion of bones');
INSERT INTO `symptomlist` VALUES ( 2562003,'Athanasia trifurcata poisoning');
INSERT INTO `symptomlist` VALUES ( 2576002,'Trachoma');
INSERT INTO `symptomlist` VALUES ( 2581006,'Clasp-knife effect');
INSERT INTO `symptomlist` VALUES ( 2582004,'Deep third degree burn of multiple sites of lower limb');
INSERT INTO `symptomlist` VALUES ( 2583009,'Chiaris network');
INSERT INTO `symptomlist` VALUES ( 2584003,'Cerebral degeneration in childhood');
INSERT INTO `symptomlist` VALUES ( 2585002,'Pneumococcal pleurisy');
INSERT INTO `symptomlist` VALUES ( 2589008,'Acute dacryoadenitis');
INSERT INTO `symptomlist` VALUES ( 2591000,'Crushing injury of shoulder region');
INSERT INTO `symptomlist` VALUES ( 2593002,'Dubowitzs syndrome');
INSERT INTO `symptomlist` VALUES ( 2602008,'Hemarthrosis of shoulder region');
INSERT INTO `symptomlist` VALUES ( 2606006,'Furuncle of perineum');
INSERT INTO `symptomlist` VALUES ( 2615004,'Follicular cyst of ovary');
INSERT INTO `symptomlist` VALUES ( 2618002,'Chronic recurrent major depressive disorder');
INSERT INTO `symptomlist` VALUES ( 2622007,'Infected ulcer of skin');
INSERT INTO `symptomlist` VALUES ( 2624008,'Prepubertal periodontitis');
INSERT INTO `symptomlist` VALUES ( 2625009,'Senter syndrome');
INSERT INTO `symptomlist` VALUES ( 2630008,'Open wound of finger without complication');
INSERT INTO `symptomlist` VALUES ( 2634004,'Decreased blood erythrocyte volume');
INSERT INTO `symptomlist` VALUES ( 2638001,'Hypercalcemia due to a drug');
INSERT INTO `symptomlist` VALUES ( 2640006,'Clinical stage IV');
INSERT INTO `symptomlist` VALUES ( 2651006,'Closed traumatic dislocation of elbow joint (disorder)');
INSERT INTO `symptomlist` VALUES ( 2655002,'Invalidism');
INSERT INTO `symptomlist` VALUES ( 2657005,'Overflow proteinuria');
INSERT INTO `symptomlist` VALUES ( 2663001,'Palpatory proteinuria');
INSERT INTO `symptomlist` VALUES ( 2665008,'Coordinate convulsion');
INSERT INTO `symptomlist` VALUES ( 2683000,'Nonvenomous insect bite of axilla without infection');
INSERT INTO `symptomlist` VALUES ( 2689001,'Dominant dystrophic epidermolysis bullosa with absence of skin');
INSERT INTO `symptomlist` VALUES ( 2694001,'Myelophthisic anemia');
INSERT INTO `symptomlist` VALUES ( 2704003,'Acute disease');
INSERT INTO `symptomlist` VALUES ( 2707005,'Necrotizing enterocolitis in fetus OR newborn');
INSERT INTO `symptomlist` VALUES ( 2713001,'Closed pneumothorax');
INSERT INTO `symptomlist` VALUES ( 2724004,'Recruitment');
INSERT INTO `symptomlist` VALUES ( 2725003,'Previous abnormality of glucose tolerance');
INSERT INTO `symptomlist` VALUES ( 2733002,'Heel pain');
INSERT INTO `symptomlist` VALUES ( 2736005,'Atrophoderma vermiculatum');
INSERT INTO `symptomlist` VALUES ( 2740001,'Gouty proteinuria');
INSERT INTO `symptomlist` VALUES ( 2749000,'Congenital deformity of hip joint');
INSERT INTO `symptomlist` VALUES ( 2751001,'Fibrocalculous pancreatic diabetes');
INSERT INTO `symptomlist` VALUES ( 2761008,'Decreased stool caliber');
INSERT INTO `symptomlist` VALUES ( 2764000,'Articular crepitation');
INSERT INTO `symptomlist` VALUES ( 2770006,'Fetal or neonatal effect of antibiotic transmitted via placenta and/or breast milk (disorder)');
INSERT INTO `symptomlist` VALUES ( 2772003,'Acquired epidermolysis bullosa');
INSERT INTO `symptomlist` VALUES ( 2775001,'Loose body in joint');
INSERT INTO `symptomlist` VALUES ( 2776000,'Delirium');
INSERT INTO `symptomlist` VALUES ( 2782002,'Temporomandibular dysplasia');
INSERT INTO `symptomlist` VALUES ( 2783007,'Gastrojejunal ulcer without hemorrhage AND without perforation');
INSERT INTO `symptomlist` VALUES ( 2786004,'Epithelial ovarian tumor, FIGO stage III');
INSERT INTO `symptomlist` VALUES ( 2790002,'Impairment level: one eye: total impairment: other eye: not specified');
INSERT INTO `symptomlist` VALUES ( 2805007,'Phosmet poisoning');
INSERT INTO `symptomlist` VALUES ( 2806008,'Impaired psychomotor development');
INSERT INTO `symptomlist` VALUES ( 2807004,'Chronic gastrojejunal ulcer with perforation');
INSERT INTO `symptomlist` VALUES ( 2808009,'Infection by Prosthenorchis elegans');
INSERT INTO `symptomlist` VALUES ( 2815001,'Sexual pyromania');
INSERT INTO `symptomlist` VALUES ( 2816000,'Dilated cardiomyopathy secondary to myotonic dystrophy');
INSERT INTO `symptomlist` VALUES ( 2818004,'Congenital vascular anomaly of eye');
INSERT INTO `symptomlist` VALUES ( 2819007,'Poisoning by magnesium sulfate');
INSERT INTO `symptomlist` VALUES ( 2825006,'Gingival abrasion');
INSERT INTO `symptomlist` VALUES ( 2828008,'Congenital stenosis of nares');
INSERT INTO `symptomlist` VALUES ( 2829000,'Uhls disease');
INSERT INTO `symptomlist` VALUES ( 2835000,'Traumatic cardiac hemolytic anemia');
INSERT INTO `symptomlist` VALUES ( 2836004,'Toxic effect of butane');
INSERT INTO `symptomlist` VALUES ( 2838003,'Piblokto');
INSERT INTO `symptomlist` VALUES ( 2850009,'Infection by Schistosoma incognitum');
INSERT INTO `symptomlist` VALUES ( 2853006,'Macular keratitis');
INSERT INTO `symptomlist` VALUES ( 2856003,'Vitamin A-responsive dermatosis');
INSERT INTO `symptomlist` VALUES ( 2858002,'Puerperal septicemia');
INSERT INTO `symptomlist` VALUES ( 2884008,'Weill-Marchesani syndrome');
INSERT INTO `symptomlist` VALUES ( 2893009,'Anomaly of chromosome pair 10');
INSERT INTO `symptomlist` VALUES ( 2897005,'Thrombocytopenia due to immune destruction');
INSERT INTO `symptomlist` VALUES ( 2899008,'Thought block');
INSERT INTO `symptomlist` VALUES ( 2901004,'Melena');
INSERT INTO `symptomlist` VALUES ( 2902006,'Decreased lymphocyte life span');
INSERT INTO `symptomlist` VALUES ( 2904007,'Male infertility');
INSERT INTO `symptomlist` VALUES ( 2910007,'Discharge from penis');
INSERT INTO `symptomlist` VALUES ( 2912004,'Cystic-bullous disease of the lung');
INSERT INTO `symptomlist` VALUES ( 2917005,'Transient hypothyroidism');
INSERT INTO `symptomlist` VALUES ( 2918000,'Infection due to Bacteroides');
INSERT INTO `symptomlist` VALUES ( 2919008,'Nausea, vomiting and diarrhea');
INSERT INTO `symptomlist` VALUES ( 2929001,'Occlusion of artery');
INSERT INTO `symptomlist` VALUES ( 2935001,'Poisoning by antiasthmatic');
INSERT INTO `symptomlist` VALUES ( 2946003,'Osmotic diarrhea');
INSERT INTO `symptomlist` VALUES ( 2951009,'Atopic cataract');
INSERT INTO `symptomlist` VALUES ( 2955000,'Chronic ulcerative pulpitis');
INSERT INTO `symptomlist` VALUES ( 2965006,'Congenital alopecia');
INSERT INTO `symptomlist` VALUES ( 2967003,'Non-comitant strabismus');
INSERT INTO `symptomlist` VALUES ( 2973002,'Pelvic organ injury without open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 2978006,'Aneurysm of conjunctiva');
INSERT INTO `symptomlist` VALUES ( 2981001,'Abdominal pulsatile mass');
INSERT INTO `symptomlist` VALUES ( 2989004,'Complication following molar AND/OR ectopic pregnancy');
INSERT INTO `symptomlist` VALUES ( 2990008,'Lymphocytic leukemoid reaction');
INSERT INTO `symptomlist` VALUES ( 2992000,'Pigmentary pallidal degeneration');
INSERT INTO `symptomlist` VALUES ( 2994004,'Brain fag');
INSERT INTO `symptomlist` VALUES ( 2999009,'Injury of ear');
INSERT INTO `symptomlist` VALUES ( 3002002,'Hemorrhage of thyroid');
INSERT INTO `symptomlist` VALUES ( 3004001,'Congenital dilatation of esophagus');
INSERT INTO `symptomlist` VALUES ( 3006004,'Disturbance of consciousness');
INSERT INTO `symptomlist` VALUES ( 3009006,'Solanum malacoxylon poisoning');
INSERT INTO `symptomlist` VALUES ( 3013004,'Open wound of ear drum without complication');
INSERT INTO `symptomlist` VALUES ( 3014005,'Id reaction');
INSERT INTO `symptomlist` VALUES ( 3018008,'Penetration of eyeball with magnetic foreign body');
INSERT INTO `symptomlist` VALUES ( 3019000,'Closed anterior dislocation of elbow');
INSERT INTO `symptomlist` VALUES ( 3021005,'Normal gastric acidity');
INSERT INTO `symptomlist` VALUES ( 3023008,'Acute peptic ulcer without hemorrhage, without perforation AND without obstruction');
INSERT INTO `symptomlist` VALUES ( 3032005,'Nonvenomous insect bite of cheek without infection');
INSERT INTO `symptomlist` VALUES ( 3033000,'Bone AND/OR joint disorder of pelvis in mother complicating pregnancy, childbirth AND/OR puerperium');
INSERT INTO `symptomlist` VALUES ( 3038009,'Acute lymphangitis of umbilicus');
INSERT INTO `symptomlist` VALUES ( 3044008,'Vitreous prolapse');
INSERT INTO `symptomlist` VALUES ( 3053001,'Poisoning by nitroglycerin');
INSERT INTO `symptomlist` VALUES ( 3059002,'Acute lymphangitis of thigh');
INSERT INTO `symptomlist` VALUES ( 3067005,'Blood group antigen C^u^');
INSERT INTO `symptomlist` VALUES ( 3071008,'Widow');
INSERT INTO `symptomlist` VALUES ( 3072001,'Hormone-induced hypopituitarism');
INSERT INTO `symptomlist` VALUES ( 3073006,'Ruvalcaba syndrome');
INSERT INTO `symptomlist` VALUES ( 3084004,'Nonvenomous insect bite of gum without infection');
INSERT INTO `symptomlist` VALUES ( 3089009,'Disability evaluation, impairment, class 7');
INSERT INTO `symptomlist` VALUES ( 3094009,'Vomiting in infants AND/OR children');
INSERT INTO `symptomlist` VALUES ( 3095005,'Induced malaria');
INSERT INTO `symptomlist` VALUES ( 3097002,'Superficial injury of lip with infection');
INSERT INTO `symptomlist` VALUES ( 3098007,'Rupture of interventricular septum');
INSERT INTO `symptomlist` VALUES ( 3109008,'Secondary dysthymia early onset');
INSERT INTO `symptomlist` VALUES ( 3110003,'Acute otitis media');
INSERT INTO `symptomlist` VALUES ( 3119002,'Brain stem laceration with open intracranial wound AND loss of consciousness');
INSERT INTO `symptomlist` VALUES ( 3129009,'Infarction of ovary');
INSERT INTO `symptomlist` VALUES ( 3135009,'Swimmers ear');
INSERT INTO `symptomlist` VALUES ( 3140001,'Citrullinemia, subacute type');
INSERT INTO `symptomlist` VALUES ( 3144005,'Staphylococcal pleurisy');
INSERT INTO `symptomlist` VALUES ( 3158007,'Panic disorder with agoraphobia, agoraphobic avoidance in partial remission AND panic attacks in partial remission');
INSERT INTO `symptomlist` VALUES ( 3160009,'Female infertility of cervical origin');
INSERT INTO `symptomlist` VALUES ( 3163006,'Acute adenoviral follicular conjunctivitis');
INSERT INTO `symptomlist` VALUES ( 3168002,'Thrombophlebitis of intracranial venous sinus');
INSERT INTO `symptomlist` VALUES ( 3185000,'Mood-congruent delusion');
INSERT INTO `symptomlist` VALUES ( 3199001,'Sprain of shoulder');
INSERT INTO `symptomlist` VALUES ( 3200003,'Sacrocoxalgia');
INSERT INTO `symptomlist` VALUES ( 3208005,'Open wound of ossicles without complication');
INSERT INTO `symptomlist` VALUES ( 3214003,'Invasive pulmonary aspergillosis');
INSERT INTO `symptomlist` VALUES ( 3217005,'Open dislocation of sixth cervical vertebra');
INSERT INTO `symptomlist` VALUES ( 3218000,'Mycosis');
INSERT INTO `symptomlist` VALUES ( 3219008,'Disease type AND/OR category unknown');
INSERT INTO `symptomlist` VALUES ( 3228009,'Closed fracture of shaft of radius');
INSERT INTO `symptomlist` VALUES ( 3229001,'Ulcer of trachea');
INSERT INTO `symptomlist` VALUES ( 3230006,'Illegal abortion with afibrinogenemia');
INSERT INTO `symptomlist` VALUES ( 3238004,'Pericarditis');
INSERT INTO `symptomlist` VALUES ( 3239007,'Lymphocyte disorder');
INSERT INTO `symptomlist` VALUES ( 3253007,'Discoloration of skin');
INSERT INTO `symptomlist` VALUES ( 3254001,'Infection by Strongyloides westeri');
INSERT INTO `symptomlist` VALUES ( 3259006,'Homeria species poisoning');
INSERT INTO `symptomlist` VALUES ( 3261002,'Migratory osteolysis');
INSERT INTO `symptomlist` VALUES ( 3263004,'Verumontanitis');
INSERT INTO `symptomlist` VALUES ( 3272007,'Stomatocytosis');
INSERT INTO `symptomlist` VALUES ( 3274008,'Flat chest');
INSERT INTO `symptomlist` VALUES ( 3275009,'Behcets syndrome, vascular type');
INSERT INTO `symptomlist` VALUES ( 3276005,'Toad poisoning');
INSERT INTO `symptomlist` VALUES ( 3277001,'Terminal mood insomnia');
INSERT INTO `symptomlist` VALUES ( 3282008,'Welders keratitis');
INSERT INTO `symptomlist` VALUES ( 3283003,'Feeling of sand or foreign body in eye');
INSERT INTO `symptomlist` VALUES ( 3286006,'Patient status determination, greatly improved');
INSERT INTO `symptomlist` VALUES ( 3289004,'Anisometropia');
INSERT INTO `symptomlist` VALUES ( 3291007,'Closed fracture of two ribs');
INSERT INTO `symptomlist` VALUES ( 3298001,'Amnestic disorder');
INSERT INTO `symptomlist` VALUES ( 3303004,'Disease due to Arenavirus');
INSERT INTO `symptomlist` VALUES ( 3304005,'Bronchial compression');
INSERT INTO `symptomlist` VALUES ( 3305006,'Disorder of lymphatics');
INSERT INTO `symptomlist` VALUES ( 3308008,'Atrophic-hyperplastic gastritis');
INSERT INTO `symptomlist` VALUES ( 3310005,'Foreign body granuloma of skin');
INSERT INTO `symptomlist` VALUES ( 3321001,'Renal abscess');
INSERT INTO `symptomlist` VALUES ( 3323003,'Leukoplakia of penis');
INSERT INTO `symptomlist` VALUES ( 3327002,'Jerk nystagmus');
INSERT INTO `symptomlist` VALUES ( 3331008,'Open fracture of neck of metacarpal bone');
INSERT INTO `symptomlist` VALUES ( 3344003,'Toxic labyrinthitis');
INSERT INTO `symptomlist` VALUES ( 3345002,'Idiopathic osteoporosis');
INSERT INTO `symptomlist` VALUES ( 3355003,'Poisoning by anti-common cold drug');
INSERT INTO `symptomlist` VALUES ( 3358001,'Lichen ruber moniliformis');
INSERT INTO `symptomlist` VALUES ( 3368006,'Dull chest pain');
INSERT INTO `symptomlist` VALUES ( 3376008,'Pseudoptyalism');
INSERT INTO `symptomlist` VALUES ( 3381004,'Open fracture of astragalus');
INSERT INTO `symptomlist` VALUES ( 3387000,'Auditory discrimination aphasia');
INSERT INTO `symptomlist` VALUES ( 3391005,'Negative for tumor cells');
INSERT INTO `symptomlist` VALUES ( 3398004,'Cadmium poisoning');
INSERT INTO `symptomlist` VALUES ( 3415004,'Cyanosis');
INSERT INTO `symptomlist` VALUES ( 3419005,'Faucial diphtheria');
INSERT INTO `symptomlist` VALUES ( 3421000,'Open fracture of orbital floor (blow-out)');
INSERT INTO `symptomlist` VALUES ( 3424008,'Tachycardia');
INSERT INTO `symptomlist` VALUES ( 3426005,'Retained magnetic intraocular foreign body');
INSERT INTO `symptomlist` VALUES ( 3427001,'Nonglucosuric melituria');
INSERT INTO `symptomlist` VALUES ( 3434004,'Myotonia');
INSERT INTO `symptomlist` VALUES ( 3439009,'SCID due to absent peripheral T cell maturation');
INSERT INTO `symptomlist` VALUES ( 3441005,'Disease of sebaceous glands');
INSERT INTO `symptomlist` VALUES ( 3446000,'Open fracture of T7-T12 level with spinal cord injury');
INSERT INTO `symptomlist` VALUES ( 3449007,'Finger agnosia');
INSERT INTO `symptomlist` VALUES ( 3456001,'Chronic progressive non-hereditary chorea');
INSERT INTO `symptomlist` VALUES ( 3458000,'Polymyositis ossificans');
INSERT INTO `symptomlist` VALUES ( 3461004,'Deep third degree burn of thumb');
INSERT INTO `symptomlist` VALUES ( 3464007,'Infection by Oesophagostomum dentatum');
INSERT INTO `symptomlist` VALUES ( 3468005,'Neonatal infective mastitis');
INSERT INTO `symptomlist` VALUES ( 3469002,'Second degree burn of thumb');
INSERT INTO `symptomlist` VALUES ( 3472009,'Spondylolisthesis, grade 4');
INSERT INTO `symptomlist` VALUES ( 3474005,'Glycine max poisoning');
INSERT INTO `symptomlist` VALUES ( 3480002,'Burn of wrist');
INSERT INTO `symptomlist` VALUES ( 3482005,'Postoperative esophagitis');
INSERT INTO `symptomlist` VALUES ( 3483000,'Chronic peptic ulcer with perforation');
INSERT INTO `symptomlist` VALUES ( 3487004,'Candidiasis of lung');
INSERT INTO `symptomlist` VALUES ( 3500002,'Open wound of ossicles with complication');
INSERT INTO `symptomlist` VALUES ( 3502005,'Cervical lymphadenitis');
INSERT INTO `symptomlist` VALUES ( 3503000,'Gender identity disorder of adolescence, previously asexual');
INSERT INTO `symptomlist` VALUES ( 3506008,'Stenosis of retinal artery');
INSERT INTO `symptomlist` VALUES ( 3507004,'Abscess of thigh');
INSERT INTO `symptomlist` VALUES ( 3511005,'Infectious thyroiditis');
INSERT INTO `symptomlist` VALUES ( 3514002,'Peribronchial fibrosis of lung');
INSERT INTO `symptomlist` VALUES ( 3519007,'Disorder of synovium');
INSERT INTO `symptomlist` VALUES ( 3528008,'Restricted carbohydrate fat controlled diet');
INSERT INTO `symptomlist` VALUES ( 3529000,'Infection by Sanguinicola');
INSERT INTO `symptomlist` VALUES ( 3530005,'Bipolar I disorder, single manic episode, in full remission');
INSERT INTO `symptomlist` VALUES ( 3531009,'Intrapsychic conflict');
INSERT INTO `symptomlist` VALUES ( 3533007,'Pustular bacterid');
INSERT INTO `symptomlist` VALUES ( 3539006,'Enteromenia');
INSERT INTO `symptomlist` VALUES ( 3542000,'Laceration extending into parenchyma of spleen with open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 3544004,'Hair-splitting');
INSERT INTO `symptomlist` VALUES ( 3545003,'Diastolic dysfunction');
INSERT INTO `symptomlist` VALUES ( 3548001,'Brachial plexus lesion');
INSERT INTO `symptomlist` VALUES ( 3549009,'Pancreatic acinar atrophy');
INSERT INTO `symptomlist` VALUES ( 3558002,'Mesenteric infarction');
INSERT INTO `symptomlist` VALUES ( 3560000,'Bilateral recurrent inguinal hernia');
INSERT INTO `symptomlist` VALUES ( 3570003,'Increased blood erythrocyte volume');
INSERT INTO `symptomlist` VALUES ( 3571004,'Megaloblastic anemia due to pancreatic insufficiency');
INSERT INTO `symptomlist` VALUES ( 3577000,'Retinal lattice degeneration');
INSERT INTO `symptomlist` VALUES ( 3585009,'Blinking');
INSERT INTO `symptomlist` VALUES ( 3586005,'Psychogenic fugue');
INSERT INTO `symptomlist` VALUES ( 3589003,'Syphilitic pericarditis');
INSERT INTO `symptomlist` VALUES ( 3590007,'Enteroenteric fistula');
INSERT INTO `symptomlist` VALUES ( 3591006,'Metabolic acidosis, NAG, bicarbonate losses');
INSERT INTO `symptomlist` VALUES ( 3598000,'Partial recent retinal detachment with single defect');
INSERT INTO `symptomlist` VALUES ( 3611003,'Demeton poisoning');
INSERT INTO `symptomlist` VALUES ( 3633001,'Abscess of hand');
INSERT INTO `symptomlist` VALUES ( 3634007,'Legal abortion complicated by metabolic disorder');
INSERT INTO `symptomlist` VALUES ( 3639002,'Glossoptosis');
INSERT INTO `symptomlist` VALUES ( 3640000,'Late effect of traumatic amputation');
INSERT INTO `symptomlist` VALUES ( 3641001,'Infection by Coenurosis serialis');
INSERT INTO `symptomlist` VALUES ( 3642008,'Deficiency of steryl-sulfatase');
INSERT INTO `symptomlist` VALUES ( 3644009,'Macerated skin');
INSERT INTO `symptomlist` VALUES ( 3649004,'Contusion of multiple sites of trunk');
INSERT INTO `symptomlist` VALUES ( 3650004,'Congenital absence of liver');
INSERT INTO `symptomlist` VALUES ( 3652007,'Overproduction of growth hormone');
INSERT INTO `symptomlist` VALUES ( 3657001,'Osteospermum species poisoning');
INSERT INTO `symptomlist` VALUES ( 3662000,'Paraesophageal hernia');
INSERT INTO `symptomlist` VALUES ( 3677008,'Academic problem');
INSERT INTO `symptomlist` VALUES ( 3680009,'Monocephalus tripus dibrachius');
INSERT INTO `symptomlist` VALUES ( 3681008,'Thrombophlebitis of torcular Herophili');
INSERT INTO `symptomlist` VALUES ( 3696007,'Nonulcer dyspepsia');
INSERT INTO `symptomlist` VALUES ( 3699000,'Transverse deficiency of upper limb');
INSERT INTO `symptomlist` VALUES ( 3703002,'Ischiatic hernia with gangrene');
INSERT INTO `symptomlist` VALUES ( 3704008,'Diffuse endocapillary proliferative glomerulonephritis');
INSERT INTO `symptomlist` VALUES ( 3705009,'Congenital anomaly of anterior chamber of eye');
INSERT INTO `symptomlist` VALUES ( 3716002,'Goiter');
INSERT INTO `symptomlist` VALUES ( 3720003,'Abnormal presence of hemoglobin');
INSERT INTO `symptomlist` VALUES ( 3723001,'Arthritis');
INSERT INTO `symptomlist` VALUES ( 3733009,'Congenital eventration of right crus of diaphragm');
INSERT INTO `symptomlist` VALUES ( 3738000,'Viral hepatitis');
INSERT INTO `symptomlist` VALUES ( 3744001,'Hyperlipoproteinemia');
INSERT INTO `symptomlist` VALUES ( 3747008,'Ejection click');
INSERT INTO `symptomlist` VALUES ( 3750006,'Arteriospasm');
INSERT INTO `symptomlist` VALUES ( 3751005,'Contusion of labium');
INSERT INTO `symptomlist` VALUES ( 3752003,'Trichuriasis');
INSERT INTO `symptomlist` VALUES ( 3754002,'Dysplasia of vagina');
INSERT INTO `symptomlist` VALUES ( 3755001,'Pityriasis rubra pilaris');
INSERT INTO `symptomlist` VALUES ( 3756000,'Static ataxia');
INSERT INTO `symptomlist` VALUES ( 3759007,'Injury of heart with open wound into thorax');
INSERT INTO `symptomlist` VALUES ( 3760002,'Familial multiple factor deficiency syndrome, type V');
INSERT INTO `symptomlist` VALUES ( 3762005,'Bilateral recurrent femoral hernia with gangrene');
INSERT INTO `symptomlist` VALUES ( 3763000,'Expected bereavement');
INSERT INTO `symptomlist` VALUES ( 3783004,'Enamel pearls');
INSERT INTO `symptomlist` VALUES ( 3797007,'Periodontal cyst');
INSERT INTO `symptomlist` VALUES ( 3798002,'Premature birth of identical twins, both stillborn');
INSERT INTO `symptomlist` VALUES ( 3815005,'Crohns disease of rectum');
INSERT INTO `symptomlist` VALUES ( 3820005,'Inner ear conductive hearing loss');
INSERT INTO `symptomlist` VALUES ( 3827008,'Aneurysm of artery of neck');
INSERT INTO `symptomlist` VALUES ( 3830001,'Subcutaneous emphysema');
INSERT INTO `symptomlist` VALUES ( 3841004,'Blister of cheek with infection');
INSERT INTO `symptomlist` VALUES ( 3845008,'Congenital duplication of intestine');
INSERT INTO `symptomlist` VALUES ( 3855007,'Disorder of pancreas');
INSERT INTO `symptomlist` VALUES ( 3885002,'ABO isoimmunization affecting pregnancy');
INSERT INTO `symptomlist` VALUES ( 3886001,'Congenital fecaliths');
INSERT INTO `symptomlist` VALUES ( 3899003,'Neutropenic typhlitis');
INSERT INTO `symptomlist` VALUES ( 3900008,'Mixed sensory-motor polyneuropathy');
INSERT INTO `symptomlist` VALUES ( 3902000,'Non dose-related drug-induced neutropenia');
INSERT INTO `symptomlist` VALUES ( 3903005,'Traumatic pneumothorax without open wound into thorax');
INSERT INTO `symptomlist` VALUES ( 3908001,'Infestation by Haematopinus');
INSERT INTO `symptomlist` VALUES ( 3909009,'Coeur en sabot');
INSERT INTO `symptomlist` VALUES ( 3913002,'Injury of gastrointestinal tract with open wound into abdominal cavity');
INSERT INTO `symptomlist` VALUES ( 3914008,'Mental disorder in childhood');
INSERT INTO `symptomlist` VALUES ( 3928002,'Zika virus disease');
INSERT INTO `symptomlist` VALUES ( 3939004,'Bacterial colony density, transparent');
INSERT INTO `symptomlist` VALUES ( 3944006,'Steroid sulfatase deficiency');
INSERT INTO `symptomlist` VALUES ( 3947004,'High oxygen affinity hemoglobin polycythemia');
INSERT INTO `symptomlist` VALUES ( 3950001,'Birth');
INSERT INTO `symptomlist` VALUES ( 3951002,'Proctitis');
INSERT INTO `symptomlist` VALUES ( 3972004,'Primary insomnia');
INSERT INTO `symptomlist` VALUES ( 3975002,'Deep third degree burn of lower limb');
INSERT INTO `symptomlist` VALUES ( 3978000,'Hemolytic anemia due to warm antibody');
INSERT INTO `symptomlist` VALUES ( 3987009,'Congenital absence of trachea');
INSERT INTO `symptomlist` VALUES ( 3993001,'Infection by Muellerius');
INSERT INTO `symptomlist` VALUES ( 3999002,'Acute pyelitis without renal medullary necrosis');
INSERT INTO `symptomlist` VALUES ( 4003003,'Disease due to Alphavirus');
INSERT INTO `symptomlist` VALUES ( 4006006,'Fetal tachycardia affecting management of mother');
INSERT INTO `symptomlist` VALUES ( 4009004,'Lower urinary tract infectious disease');
INSERT INTO `symptomlist` VALUES ( 4016003,'Empyema of mastoid');
INSERT INTO `symptomlist` VALUES ( 4017007,'Increased stratum corneum adhesiveness');
INSERT INTO `symptomlist` VALUES ( 4022007,'Vulvitis circumscripta plasmacellularis');
INSERT INTO `symptomlist` VALUES ( 4026005,'Interstitial mastitis associated with childbirth');
INSERT INTO `symptomlist` VALUES ( 4030008,'Le Dantec virus disease');
INSERT INTO `symptomlist` VALUES ( 4038001,'Myrotheciotoxicosis');
INSERT INTO `symptomlist` VALUES ( 4039009,'Multiple vitamin deficiency disease');
INSERT INTO `symptomlist` VALUES ( 4040006,'Hassall-Henle bodies');
INSERT INTO `symptomlist` VALUES ( 4041005,'Congenital anomaly of macula');
INSERT INTO `symptomlist` VALUES ( 4046000,'Degenerative spondylolisthesis');
INSERT INTO `symptomlist` VALUES ( 4062006,'Lumbosacral plexus lesion');
INSERT INTO `symptomlist` VALUES ( 4063001,'Achillodynia');
INSERT INTO `symptomlist` VALUES ( 4069002,'Anoxic brain damage during AND/OR resulting from a procedure');
INSERT INTO `symptomlist` VALUES ( 4070001,'Palinphrasia');
INSERT INTO `symptomlist` VALUES ( 4075006,'Peganum harmala poisoning');
INSERT INTO `symptomlist` VALUES ( 4082005,'Syphilitic myocarditis');
INSERT INTO `symptomlist` VALUES ( 4088009,'Acquired hydrocephalus');
INSERT INTO `symptomlist` VALUES ( 4089001,'Meningococcemia');
INSERT INTO `symptomlist` VALUES ( 4103001,'Complex partial seizures with consciousness impaired');
INSERT INTO `symptomlist` VALUES ( 4106009,'Rotator cuff syndrome');
INSERT INTO `symptomlist` VALUES ( 4107000,'Infertile male syndrome');
INSERT INTO `symptomlist` VALUES ( 4113009,'Arrested hydrocephalus');
INSERT INTO `symptomlist` VALUES ( 4120002,'Bronchiolitis');
INSERT INTO `symptomlist` VALUES ( 4124006,'Nonvenomous insect bite of vagina with infection');
INSERT INTO `symptomlist` VALUES ( 4127004,'Prostatic obstruction');
INSERT INTO `symptomlist` VALUES ( 4129001,'Argyll-Robertson pupil');
INSERT INTO `symptomlist` VALUES ( 4135001,'11p partial monosomy syndrome');
INSERT INTO `symptomlist` VALUES ( 4136000,'Macrodactyly of toe (disorder)');
INSERT INTO `symptomlist` VALUES ( 4142001,'Muscular asthenopia');
INSERT INTO `symptomlist` VALUES ( 4160001,'Congenital anomaly of upper respiratory system');
INSERT INTO `symptomlist` VALUES ( 4168008,'Tibial plateau chondromalacia');
INSERT INTO `symptomlist` VALUES ( 4170004,'Ehlers-Danlos syndrome, procollagen proteinase resistant');
INSERT INTO `symptomlist` VALUES ( 4174008,'Placenta tripartita');
INSERT INTO `symptomlist` VALUES ( 4175009,'Oestrosis');
INSERT INTO `symptomlist` VALUES ( 4178006,'Partial recent retinal detachment with multiple defects');
INSERT INTO `symptomlist` VALUES ( 4181001,'Normal peak expiratory flow rate');
INSERT INTO `symptomlist` VALUES ( 4183003,'Charcot-Marie-Tooth disease, type IC');
INSERT INTO `symptomlist` VALUES ( 4184009,'Congenital anomaly of endocrine gland');
INSERT INTO `symptomlist` VALUES ( 4195003,'Congenital duplication of anus');
INSERT INTO `symptomlist` VALUES ( 4197006,'Disability evaluation, impairment, class 5');
INSERT INTO `symptomlist` VALUES ( 4199009,'18p partial trisomy syndrome');
INSERT INTO `symptomlist` VALUES ( 4208000,'Closed multiple fractures of both lower limbs');
INSERT INTO `symptomlist` VALUES ( 4210003,'Ocular hypertension');
INSERT INTO `symptomlist` VALUES ( 4223005,'Parkinsonism due to drug');
INSERT INTO `symptomlist` VALUES ( 4224004,'Complication of infusion');
INSERT INTO `symptomlist` VALUES ( 4225003,'Tuberculosis of nose');
INSERT INTO `symptomlist` VALUES ( 4229009,'Atrophy of globe');
INSERT INTO `symptomlist` VALUES ( 4232007,'Chronic vulvitis');
INSERT INTO `symptomlist` VALUES ( 4237001,'Suppurative pulpitis');
INSERT INTO `symptomlist` VALUES ( 4240001,'Rupture of aorta');
INSERT INTO `symptomlist` VALUES ( 4241002,'Listeriosis');
INSERT INTO `symptomlist` VALUES ( 4242009,'18q partial monosomy syndrome');
INSERT INTO `symptomlist` VALUES ( 4248008,'Synovitis AND/OR tenosynovitis associated with another disease');
INSERT INTO `symptomlist` VALUES ( 4249000,'Poor peripheral circulation');
INSERT INTO `symptomlist` VALUES ( 4260009,'Sacral spinal cord injury without bone injury');
INSERT INTO `symptomlist` VALUES ( 4262001,'Phlebitis of superior sagittal sinus');
INSERT INTO `symptomlist` VALUES ( 4264000,'Chronic pericoronitis');
INSERT INTO `symptomlist` VALUES ( 4269005,'Chronic gastrojejunal ulcer without hemorrhage AND without perforation');
INSERT INTO `symptomlist` VALUES ( 4273008,'Closed posterior dislocation of elbow');
INSERT INTO `symptomlist` VALUES ( 4275001,'Spasm of conjugate gaze');
INSERT INTO `symptomlist` VALUES ( 4278004,'Superficial foreign body of axilla without major open wound but with infection');
INSERT INTO `symptomlist` VALUES ( 4283007,'Mirizzis syndrome');
INSERT INTO `symptomlist` VALUES ( 4287008,'Chordee');
INSERT INTO `symptomlist` VALUES ( 4294006,'Isosexual precocious puberty');
INSERT INTO `symptomlist` VALUES ( 4300009,'Deep third degree burn of forearm');
INSERT INTO `symptomlist` VALUES ( 4301008,'Autoimmune state');
INSERT INTO `symptomlist` VALUES ( 4306003,'Cluster B personality disorder');
INSERT INTO `symptomlist` VALUES ( 4307007,'Pregestational diabetes mellitus AND/OR impaired glucose tolerance, modified White class F');
INSERT INTO `symptomlist` VALUES ( 4313003,'Acardiacus anceps');
INSERT INTO `symptomlist` VALUES ( 4316006,'Myometritis');
INSERT INTO `symptomlist` VALUES ( 4320005,'Factor V deficiency');
INSERT INTO `symptomlist` VALUES ( 4324001,'Subacute cystitis');
INSERT INTO `symptomlist` VALUES ( 4325000,'11q partial monosomy syndrome');
INSERT INTO `symptomlist` VALUES ( 4338008,'Arnolds nerve reflex cough syndrome');
INSERT INTO `symptomlist` VALUES ( 4340003,'Acrodermatitis atrophicans chronica');
INSERT INTO `symptomlist` VALUES ( 4349002,'Open fracture of multiple sites of metacarpus');
INSERT INTO `symptomlist` VALUES ( 4354006,'Open dislocation of scapula');
INSERT INTO `symptomlist` VALUES ( 4356008,'Gingival recession');
INSERT INTO `symptomlist` VALUES ( 4359001,'Early congenital syphilis (less than 2 years)');
INSERT INTO `symptomlist` VALUES ( 4364002,'Structure of associations');
INSERT INTO `symptomlist` VALUES ( 4367009,'Hoovers sign');
INSERT INTO `symptomlist` VALUES ( 4373005,'Hippocratic nails');
INSERT INTO `symptomlist` VALUES ( 4374004,'Congenital anomaly of tricuspid valve');
INSERT INTO `symptomlist` VALUES ( 4381006,'Verbal paraphasia');
INSERT INTO `symptomlist` VALUES ( 4386001,'Bronchospasm');
INSERT INTO `symptomlist` VALUES ( 4390004,'Lithium nephropathy');
INSERT INTO `symptomlist` VALUES ( 4397001,'Partial congenital duodenal obstruction');
INSERT INTO `symptomlist` VALUES ( 4399003,'Acute hemorrhagic pancreatitis');
INSERT INTO `symptomlist` VALUES ( 4403007,'Exclamation point hair');
INSERT INTO `symptomlist` VALUES ( 4406004,'Congenital anomaly of male genital system');
INSERT INTO `symptomlist` VALUES ( 4409006,'Adenosylcobalamin and methylcobalamin synthesis defect');
INSERT INTO `symptomlist` VALUES ( 4410001,'Retroperitoneal hernia with obstruction');
INSERT INTO `symptomlist` VALUES ( 4412009,'Injury of digital nerve');
INSERT INTO `symptomlist` VALUES ( 4414005,'Infection by Setaria');
INSERT INTO `symptomlist` VALUES ( 4416007,'Heerfordts syndrome');
INSERT INTO `symptomlist` VALUES ( 4418008,'Gangrenous ergotism');
INSERT INTO `symptomlist` VALUES ( 4426000,'Abortion number 10');
INSERT INTO `symptomlist` VALUES ( 4434006,'Bloom syndrome');
INSERT INTO `symptomlist` VALUES ( 4439001,'Cyclic oculomotor paralysis');
INSERT INTO `symptomlist` VALUES ( 4441000,'Severe bipolar disorder with psychotic features');
INSERT INTO `symptomlist` VALUES ( 4445009,'Tuberculosis of genitourinary system');
INSERT INTO `symptomlist` VALUES ( 4448006,'Allergic headache');
INSERT INTO `symptomlist` VALUES ( 4451004,'Illegal abortion with renal tubular necrosis');
INSERT INTO `symptomlist` VALUES ( 4461006,'Complication of administrative procedure');
INSERT INTO `symptomlist` VALUES ( 4463009,'Familial amyloid polyneuropathy, type II');
INSERT INTO `symptomlist` VALUES ( 4464003,'Rocio virus disease');
INSERT INTO `symptomlist` VALUES ( 4465002,'Spherophakia');
INSERT INTO `symptomlist` VALUES ( 4468000,'Oppenheims gait');
INSERT INTO `symptomlist` VALUES ( 4470009,'Blanching of skin');
INSERT INTO `symptomlist` VALUES ( 4473006,'Migraine with aura');
INSERT INTO `symptomlist` VALUES ( 4477007,'Juvenile myopathy AND lactate acidosis');
INSERT INTO `symptomlist` VALUES ( 4478002,'Multiple fractures of upper AND lower limbs');
INSERT INTO `symptomlist` VALUES ( 4481007,'Abnormal gastric secretion regulation');
INSERT INTO `symptomlist` VALUES ( 4483005,'Syphilitic punched out ulcer');
INSERT INTO `symptomlist` VALUES ( 4490000,'Impairment level: better eye: moderate impairment: lesser eye: near-total impairment');
INSERT INTO `symptomlist` VALUES ( 4494009,'Diverticulitis of large intestine');
INSERT INTO `symptomlist` VALUES ( 4495005,'Congenital hypertrophy of ureteric valve');
INSERT INTO `symptomlist` VALUES ( 4499004,'Disseminated anergic leishmaniasis');
INSERT INTO `symptomlist` VALUES ( 4501007,'Tuberculous ascites');
INSERT INTO `symptomlist` VALUES ( 4506002,'Educational problem');
INSERT INTO `symptomlist` VALUES ( 4510004,'Streptococcal meningitis');
INSERT INTO `symptomlist` VALUES ( 4512007,'Group sex play');
INSERT INTO `symptomlist` VALUES ( 4519003,'Hypouricemia');
INSERT INTO `symptomlist` VALUES ( 4522001,'Dental plaque');
INSERT INTO `symptomlist` VALUES ( 4523006,'Babinski-Nageotte syndrome');
INSERT INTO `symptomlist` VALUES ( 4526003,'Poisoning by probenecid');
INSERT INTO `symptomlist` VALUES ( 4528002,'Senecio jacobea poisoning');
INSERT INTO `symptomlist` VALUES ( 4529005,'Abnormal spermatogenesis');
INSERT INTO `symptomlist` VALUES ( 4530000,'Madelungs deformity');
INSERT INTO `symptomlist` VALUES ( 4547004,'Determination of outcome, satisfactory to physician');
INSERT INTO `symptomlist` VALUES ( 4550001,'Special infant formula');
INSERT INTO `symptomlist` VALUES ( 4554005,'Intraventricular conduction defect');
INSERT INTO `symptomlist` VALUES ( 4556007,'Gastritis');
INSERT INTO `symptomlist` VALUES ( 4557003,'Preinfarction syndrome');
INSERT INTO `symptomlist` VALUES ( 4559000,'Mixed infectious disease');
INSERT INTO `symptomlist` VALUES ( 4565000,'Decreased oxygen affinity');
INSERT INTO `symptomlist` VALUES ( 4568003,'Retrosternal chest pain');
INSERT INTO `symptomlist` VALUES ( 4575002,'Acute hyponatremia');
INSERT INTO `symptomlist` VALUES ( 4576001,'Legal abortion complicated by renal failure');
INSERT INTO `symptomlist` VALUES ( 4586000,'Complication of internal fixation device');
INSERT INTO `symptomlist` VALUES ( 4592006,'S>4< gallop');
INSERT INTO `symptomlist` VALUES ( 4598005,'Osteomalacia');
INSERT INTO `symptomlist` VALUES ( 4602007,'Robin sequence');
INSERT INTO `symptomlist` VALUES ( 4619009,'Generalized-onset seizures');
INSERT INTO `symptomlist` VALUES ( 4633009,'Hymenoxys richardsonii poisoning');
INSERT INTO `symptomlist` VALUES ( 4637005,'Intrahepatic cholestasis');
INSERT INTO `symptomlist` VALUES ( 4639008,'Glanders');
INSERT INTO `symptomlist` VALUES ( 4641009,'Myxedema heart disease');
INSERT INTO `symptomlist` VALUES ( 4645000,'Senile brain amyloidosis');
INSERT INTO `symptomlist` VALUES ( 4646004,'Impairment level: one eye: profound impairment: other eye: not specified');
INSERT INTO `symptomlist` VALUES ( 4654002,'Posteruptive color change of tooth');
INSERT INTO `symptomlist` VALUES ( 4659007,'Acne fulminans');
INSERT INTO `symptomlist` VALUES ( 4661003,'Calculus of bile duct with obstruction');
INSERT INTO `symptomlist` VALUES ( 4665007,'Costal respiration');
INSERT INTO `symptomlist` VALUES ( 4667004,'Female infertility due to structural congenital anomaly of vagina');
INSERT INTO `symptomlist` VALUES ( 4669001,'Pinta, primary lesion');
INSERT INTO `symptomlist` VALUES ( 4673003,'Open fracture of lateral malleolus');
INSERT INTO `symptomlist` VALUES ( 4676006,'SLE glomerulonephritis syndrome, WHO class II');
INSERT INTO `symptomlist` VALUES ( 4688008,'Poisoning by griseofulvin');